Iter 5
LilLebowski/shortener pull request #5
Opened 2024-03-09 14:52 UTC by LilLebowski

refactor: change env parsing

2024-03-11 18:20 UTC, rktkov requested changes

2024-03-11 18:20 UTC, rktkov commented on internal/handlers/handlers.go
> +	"fmt"
import

Возьмите в привычку сортировать импортируемые пакеты следующим образом:
1. пакеты стандартной библиотеки
2. внешние установленные пакеты
3. внутренние пакеты проекта

Для того, чтобы разные автоматические инструменты их не пересортировывали, разделяйте блоки пустой строкой.

см. комментарий про порядок импорта
https://stackoverflow.com/questions/24790175/when-is-the-init-function-run

2024-03-11 18:20 UTC, rktkov commented on internal/handlers/handlers.go
> +	if reqBodyString != "" {
лучше код переписать таким образом, чтобы каждый негативный сценарий завершал выполнение, т.е.  if regBodyString == "" ... return if err != nil .. return  и т.д.
так код станет более читабельным.

2024-03-19 00:39 UTC, LilLebowski commented
@rktkov  по поводу тестов: я не понимаю почему происходит ошибка и как это исправить

2024-03-19 00:40 UTC, LilLebowski commented on internal/handlers/handlers.go
> +	"fmt"
исправила

2024-03-19 00:40 UTC, LilLebowski commented on internal/handlers/handlers.go
> +	if reqBodyString != "" {
исправила

2024-03-21 20:48 UTC, rktkov commented
По поводу падающего теста  - их можно запустить локально и проверить, где они падают: https://github.com/Yandex-Practicum/go-autotests/tree/0aaf19b8bd78b9c14a2e00f3ae38282b040cca4c

2024-03-21 20:48 UTC, rktkov approved these changes

2024-03-27 05:55 UTC, merged